import { tasks } from './tasks.js';
import { connectGuest, saveGuest, addCompletedTask, uploadPhoto, listenPhotos, ownPhoto, deletePhoto, saveGuestbook, listenGuestbook, likePhoto, listenLikes, listenRanking, listenStats } from './firebase-service.js';

(() => {
  const K='misja-wesele-pk-2026-v5', $=id=>document.getElementById(id), views=['nameView','welcomeView','drawingView','taskView','finishedView','uploadView','galleryView','guestbookView','rankingView'], levels={easy:'🟢 ŁATWE',medium:'🟡 ŚREDNIE',hard:'🔴 ODWAŻNE',legend:'✦ ZŁOTA MISJA'}, ranks=[[0,'Gość weselny'],[30,'Pogromca lodów'],[80,'Mistrz toastów'],[160,'Król parkietu'],[300,'Legenda wesela']];
  let state=read(),currentTask=null,cloud=false,file=null,uploadForTask=false,photos=[],likes=[],guestbook=[]; const esc=value=>String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function read(){try{const s=JSON.parse(localStorage.getItem(K));return {nickname:s?.nickname||'',completed:Array.isArray(s?.completed)?s.completed:[],achievements:Array.isArray(s?.achievements)?s.achievements:[],points:Number(s?.points)||0,hasGuestbook:Boolean(s?.hasGuestbook)};}catch{return {nickname:'',completed:[],achievements:[],points:0,hasGuestbook:false};}}
  function persist(){localStorage.setItem(K,JSON.stringify(state));if(cloud)saveGuest(state).catch(()=>{$('cloudStatus').textContent='Nie udało się zapisać postępu online.';});}
  function show(id){views.forEach(v=>{const e=$(v),a=v===id;e.classList.toggle('is-active',a);e.setAttribute('aria-hidden',String(!a));});}
  function update(){const d=state.completed.length,total=tasks.length,rank=[...ranks].reverse().find(([n])=>state.points>=n)[1];$('progressText').textContent=`${d} / ${total}`;$('pointsText').textContent=`${state.points} pkt`;$('rankText').textContent=rank;$('progressFill').style.width=`${d/total*100}%`;$('progressFill').parentElement.setAttribute('aria-valuenow',String(d));$('encouragement').textContent=d?`Masz już ${state.points} punktów. Kolejna misja czeka!`:'Pierwsza misja czeka na odkorkowanie.';}
  function draw(){const available=tasks.filter(t=>!state.completed.includes(t.id));if(!available.length){show('finishedView');return;}show('drawingView');setTimeout(()=>{currentTask={...available[Math.floor(Math.random()*available.length)],photoUploaded:false};$('taskText').textContent=currentTask.text;const b=$('difficultyBadge');b.className=`badge ${currentTask.level}`;b.textContent=levels[currentTask.level];$('photoRequiredNotice').classList.toggle('hidden',!currentTask.requiresPhoto);$('taskPhotoButton').classList.toggle('hidden',!currentTask.requiresPhoto);$('doneButton').disabled=currentTask.requiresPhoto;$('taskHint').textContent=currentTask.requiresPhoto?'Zrób zdjęcie i dodaj je do galerii, aby zaliczyć tę misję.':'Zrób to po swojemu i wróć po kolejne wyzwanie.';show('taskView');},650);}
  async function complete(){if(!currentTask||currentTask.requiresPhoto&&!currentTask.photoUploaded)return;if(!state.completed.includes(currentTask.id)){state.completed.push(currentTask.id);state.points+=10;persist();addCompletedTask().catch(()=>{});}const done=state.completed.length;currentTask=null;update();if([1,5,10,20,35].includes(done)&&!state.achievements.includes(done)){state.achievements.push(done);persist();$('achievementTitle').textContent=done===35?'Legenda Wesela!':`Osiągnięcie: ${done} misji`; $('achievementText').textContent=`Brawo! Zdobywasz tytuł i kolejne punkty.`;$('achievementModal').classList.add('is-open');}$('guestName').textContent=state.nickname;show(done===tasks.length?'finishedView':'welcomeView');}
  function openUpload(forTask=false){uploadForTask=forTask;$('uploadStatus').textContent=forTask?'To zdjęcie zaliczy bieżącą misję.':'';show('uploadView');}
  function selectFile(){const f=$('photoInput').files[0];if(!f)return;$('uploadStatus').textContent='';if(!f.type.startsWith('image/')||f.size>8*1024*1024){file=null;$('uploadPhotoButton').disabled=true;$('uploadStatus').textContent='Wybierz zdjęcie do 8 MB.';return;}file=f;$('selectedPhotoName').textContent=`Wybrano: ${f.name}`;$('uploadPhotoButton').disabled=!cloud;}
  async function publish(){if(!file||!cloud)return;const btn=$('uploadPhotoButton');btn.disabled=true;$('uploadStatus').textContent='Publikowanie zdjęcia…';try{await uploadPhoto(file,state,uploadForTask?currentTask:null,$('photoCaption').value.trim().slice(0,80));state.points+=5;persist();if(uploadForTask&&currentTask){currentTask.photoUploaded=true;$('doneButton').disabled=false;$('photoRequiredNotice').textContent='✓ Zdjęcie dodane — możesz zaliczyć misję.';}file=null;$('photoInput').value='';$('photoCaption').value='';$('selectedPhotoName').textContent='';$('uploadStatus').textContent='Zdjęcie opublikowane! +5 pkt';update();setTimeout(()=>show(uploadForTask?'taskView':'galleryView'),500);}catch{$('uploadStatus').textContent='Nie udało się opublikować zdjęcia. Sprawdź Storage i reguły.';btn.disabled=false;}}
  function renderPhotos(list){photos=list;const grid=$('galleryGrid');$('galleryStatus').textContent=list.length?`Najnowsze zdjęcia: ${list.length}`:'Galeria czeka na pierwsze zdjęcie.';grid.innerHTML='';const counts={};likes.forEach(l=>counts[l.photoId]=(counts[l.photoId]||0)+1);list.forEach(p=>{const card=document.createElement('div');card.className='gallery-card';const pic=document.createElement('button');pic.className='gallery-item';pic.innerHTML=`<img src="${esc(p.imageUrl)}" alt="Zdjęcie dodane przez ${esc(p.nickname||'gościa')}" loading="lazy"><span>${esc(p.caption||p.nickname||'Gość')}</span>`;pic.onclick=()=>{$('modalPhoto').src=p.imageUrl;$('modalPhotoCaption').textContent=[p.caption,p.nickname&&`Dodał/a: ${p.nickname}`,p.taskText&&`Misja: ${p.taskText}`].filter(Boolean).join(' · ');$('photoModal').classList.add('is-open');};card.append(pic);const like=document.createElement('button');like.className='like-photo';like.textContent=`♥ ${counts[p.id]||0}`;like.onclick=async()=>{try{await likePhoto(p.id);}catch{$('galleryStatus').textContent='Nie udało się dodać polubienia.';}};card.append(like);if(ownPhoto(p)){const del=document.createElement('button');del.className='delete-photo';del.textContent='Usuń';del.onclick=async()=>{if(confirm('Usunąć swoje zdjęcie?'))try{await deletePhoto(p);}catch{$('galleryStatus').textContent='Nie udało się usunąć zdjęcia.';}};card.append(del);}grid.append(card);});}
  function renderGuestbook(items){guestbook=items;const list=$('guestbookList');list.innerHTML=items.map(w=>`<article class="wish"><b>${esc(w.nickname||'Gość')}</b>${esc(w.message||'')}</article>`).join('');}
  async function writeGuestbook(){const msg=$('guestbookMessage').value.trim();if(!msg||!cloud){$('guestbookStatus').textContent='Wpisz życzenia i sprawdź połączenie.';return;}$('saveGuestbookButton').disabled=true;try{const first=await saveGuestbook(msg,state.nickname);if(first){state.hasGuestbook=true;state.points+=5;persist();update();}$('guestbookStatus').textContent=first?'Życzenia zapisane! +5 pkt':'Życzenia zaktualizowane.';}catch{$('guestbookStatus').textContent='Nie udało się zapisać życzeń.';}$('saveGuestbookButton').disabled=false;}
  function renderRanking(list){$('publicRanking').innerHTML=list.length?list.map((u,i)=>`<article class="rank-row"><b>${i+1}</b><span>${esc(u.nickname||'Gość')}</span><strong>${u.points||0} pkt · ${u.completed||0} misji</strong></article>`).join(''):'<p class="task-hint">Ranking czeka na pierwsze punkty.</p>';}
  function saveName(){const n=$('nicknameInput').value.trim().replace(/\s+/g,' ');if(!n){$('nameError').textContent='Wpisz proszę imię lub nick.';return;}state.nickname=n.slice(0,24);persist();$('guestName').textContent=state.nickname;show('welcomeView');}
  async function init(){try{const r=await connectGuest(state);state=r.state;cloud=r.mode==='cloud';localStorage.setItem(K,JSON.stringify(state));$('cloudStatus').textContent=cloud?'Wyniki i punkty zapisują się na wspólnej tablicy.':'Tryb lokalny — uzupełnij Firebase.';if(cloud){listenPhotos(renderPhotos,()=>{});listenLikes(data=>{likes=data;renderPhotos(photos);},()=>{});listenGuestbook(renderGuestbook,()=>{});listenRanking(renderRanking,()=>{});listenStats(s=>{$('globalMissions').textContent=`🎉 Goście wykonali ${s.completedTasks||0} misji`;},()=>{});}}catch{$('cloudStatus').textContent='Nie udało się połączyć z Firebase.';}$('guestName').textContent=state.nickname||'Gościu';update();show(state.nickname?'welcomeView':'nameView');}
  $('drawButton').onclick=draw;$('nextButton').onclick=draw;$('doneButton').onclick=complete;$('taskPhotoButton').onclick=()=>openUpload(true);$('openUploadButton').onclick=()=>openUpload(false);$('openGalleryButton').onclick=()=>show('galleryView');$('openGuestbookButton').onclick=()=>show('guestbookView');$('openRankingButton').onclick=()=>show('rankingView');$('backFromUploadButton').onclick=()=>show(uploadForTask?'taskView':'welcomeView');$('backFromGalleryButton').onclick=()=>show('welcomeView');$('backFromGuestbookButton').onclick=()=>show('welcomeView');$('backFromRankingButton').onclick=()=>show('welcomeView');$('photoInput').onchange=selectFile;$('uploadPhotoButton').onclick=publish;$('saveGuestbookButton').onclick=writeGuestbook;$('saveNameButton').onclick=saveName;$('nicknameInput').onkeydown=e=>{if(e.key==='Enter')saveName();};$('closeAchievement').onclick=()=>{$('achievementModal').classList.remove('is-open');};$('closePhotoModal').onclick=()=>{$('photoModal').classList.remove('is-open');};$('photoModal').onclick=e=>{if(e.target===$('photoModal'))$('photoModal').classList.remove('is-open');};$('resetButton').onclick=()=>{if(confirm('Zresetować swoje misje?')){state={...state,completed:[],achievements:[],points:0};persist();update();show('welcomeView');}};init();
})();
