import { tasks } from './tasks.js';
import { connectGuest, saveGuest, uploadPhoto, listenPhotos, ownPhoto, deletePhoto } from './firebase-service.js';

(() => {
  'use strict';
  const STORAGE_KEY='misja-wesele-pk-2026-v4', levels={easy:'🟢 ŁATWE',medium:'🟡 ŚREDNIE',hard:'🔴 ODWAŻNE',legend:'✦ ZŁOTA MISJA'}, ranks=[[0,'Gość weselny'],[3,'Pogromca lodów'],[7,'Mistrz toastów'],[12,'Król parkietu'],[20,'Legenda wesela'],[35,'Legenda nad legendami']], lines=['Dobra robota — kolejna misja czeka.','Wesele samo się nie rozkręci!','Ktoś właśnie zyskuje nowego znajomego.','Elegancko. Czas na następny krok.'];
  const $=id=>document.getElementById(id), views=['nameView','welcomeView','drawingView','taskView','finishedView','uploadView','galleryView']; let state=readState(),currentTask=null,cloudReady=false,selectedPhoto=null,stopGallery=null;
  function readState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return {nickname:typeof saved?.nickname==='string'?saved.nickname.trim().slice(0,24):'',completed:Array.isArray(saved?.completed)?saved.completed.filter(id=>tasks.some(t=>t.id===id)):[],achievements:Array.isArray(saved?.achievements)?saved.achievements:[]};}catch{return {nickname:'',completed:[],achievements:[]};}}
  function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(cloudReady)saveGuest(state).catch(()=>$('cloudStatus').textContent='Nie udało się zapisać wyniku online. Spróbuj ponownie za chwilę.');}
  function show(id){views.forEach(view=>{const el=$(view),active=view===id;el.classList.toggle('is-active',active);el.setAttribute('aria-hidden',String(!active));});}
  function draw(){const remaining=tasks.filter(t=>!state.completed.includes(t.id));if(!remaining.length){show('finishedView');celebrate();return;}show('drawingView');setTimeout(()=>{currentTask=remaining[Math.floor(Math.random()*remaining.length)];$('taskText').textContent=currentTask.text;const badge=$('difficultyBadge');badge.className=`badge ${currentTask.level}`;badge.textContent=levels[currentTask.level];$('taskHint').textContent=currentTask.level==='legend'?'To wyjątkowa misja — pokaż klasę!':'Zrób to po swojemu i wróć po kolejne wyzwanie.';show('taskView');if(currentTask.level==='legend')celebrate();},720);}
  function complete(){if(!currentTask)return;if(!state.completed.includes(currentTask.id))state.completed.push(currentTask.id);currentTask=null;save();update();checkAchievement();show(state.completed.length===tasks.length?'finishedView':'welcomeView');}
  function update(){const done=state.completed.length,total=tasks.length,rank=[...ranks].reverse().find(([n])=>done>=n)[1];$('progressText').textContent=`${done} / ${total}`;$('rankText').textContent=rank;$('progressFill').style.width=`${done/total*100}%`;$('progressFill').parentElement.setAttribute('aria-valuenow',String(done));$('encouragement').textContent=done===total?'Wszystkie misje wykonane — brawo!':done?lines[done%lines.length]:'Pierwsza misja czeka na odkorkowanie.';}
  function checkAchievement(){const done=state.completed.length,achievement={1:['Pierwszy krok','Pierwsza misja wykonana. Tak się zaczyna dobra noc!'],5:['Gość na medal','Pięć misji za Tobą. Integracja idzie wzorowo.'],10:['Mistrz Toastów','Dziesięć misji! Jesteś już częścią weselnej legendy.'],20:['Król Parkietu','Dwadzieścia misji. Formalnie: nie do zatrzymania.'],35:['Legenda Wesela','Ukończyłeś całą kolekcję misji. Czapki z głów!']}[done];if(achievement&&!state.achievements.includes(done)){state.achievements.push(done);save();$('achievementTitle').textContent=achievement[0];$('achievementText').textContent=achievement[1];$('achievementModal').classList.add('is-open');$('achievementModal').setAttribute('aria-hidden','false');celebrate();}}
  function closeModal(){$('achievementModal').classList.remove('is-open');$('achievementModal').setAttribute('aria-hidden','true');}
  function celebrate(){const box=$('confetti');box.innerHTML='';const colors=['#b48a43','#397354','#ad4d43','#785895','#f6e9bb'];for(let i=0;i<70;i++){const piece=document.createElement('i');piece.style.left=`${Math.random()*100}%`;piece.style.background=colors[i%colors.length];piece.style.setProperty('--x',`${(Math.random()-.5)*260}px`);piece.style.animationDelay=`${Math.random()*.35}s`;box.appendChild(piece);}setTimeout(()=>box.innerHTML='',2200);}
  function saveNickname(){const nickname=$('nicknameInput').value.trim().replace(/\s+/g,' ');if(!nickname){$('nameError').textContent='Wpisz proszę imię lub nick.';$('nicknameInput').focus();return;}state.nickname=nickname.slice(0,24);save();$('guestName').textContent=state.nickname;show('welcomeView');}
  function selectPhoto(){const file=$('photoInput').files[0];$('uploadStatus').textContent='';if(!file)return;if(!file.type.startsWith('image/')){selectedPhoto=null;$('uploadPhotoButton').disabled=true;$('uploadStatus').textContent='Wybierz plik graficzny.';return;}if(file.size>8*1024*1024){selectedPhoto=null;$('uploadPhotoButton').disabled=true;$('uploadStatus').textContent='Zdjęcie jest za duże. Wybierz plik do 8 MB.';return;}selectedPhoto=file;$('selectedPhotoName').textContent=`Wybrano: ${file.name}`;$('uploadPhotoButton').disabled=!cloudReady; if(!cloudReady)$('uploadStatus').textContent='Najpierw dokończ konfigurację Firebase Storage.';}
  async function publishPhoto(){if(!selectedPhoto||!cloudReady)return;const button=$('uploadPhotoButton');button.disabled=true;$('uploadStatus').textContent='Publikowanie zdjęcia…';try{await uploadPhoto(selectedPhoto,state,currentTask,$('photoCaption').value.trim().slice(0,80));$('uploadStatus').textContent='Zdjęcie opublikowane w galerii!';selectedPhoto=null;$('photoInput').value='';$('photoCaption').value='';$('selectedPhotoName').textContent='';setTimeout(()=>show('galleryView'),550);}catch(error){$('uploadStatus').textContent='Nie udało się opublikować zdjęcia. Sprawdź reguły Storage i połączenie.';button.disabled=false;}}
  function renderGallery(photos){const grid=$('galleryGrid');$('galleryStatus').textContent=photos.length?`Najnowsze zdjęcia: ${photos.length}`:'Galeria czeka na pierwsze zdjęcie.';grid.innerHTML='';photos.forEach(photo=>{const card=document.createElement('div');card.className='gallery-card';const button=document.createElement('button');button.className='gallery-item';const image=document.createElement('img');image.src=photo.imageUrl;image.alt=`Zdjęcie dodane przez ${photo.nickname||'gościa'}`;image.loading='lazy';const caption=document.createElement('span');caption.textContent=photo.caption||photo.nickname||'Gość';button.append(image,caption);button.addEventListener('click',()=>{$('modalPhoto').src=photo.imageUrl;$('modalPhotoCaption').textContent=[photo.caption,photo.nickname&&`Dodał/a: ${photo.nickname}`,photo.taskText&&`Misja: ${photo.taskText}`].filter(Boolean).join(' · ');$('photoModal').classList.add('is-open');$('photoModal').setAttribute('aria-hidden','false');});card.appendChild(button);if(ownPhoto(photo)){const remove=document.createElement('button');remove.className='delete-photo';remove.textContent='Usuń';remove.addEventListener('click',async()=>{if(!confirm('Usunąć swoje zdjęcie z galerii?'))return;remove.disabled=true;try{await deletePhoto(photo);}catch(error){$('galleryStatus').textContent='Nie udało się usunąć zdjęcia.';remove.disabled=false;}});card.appendChild(remove);}grid.appendChild(card);});}
  async function initialiseCloud(){try{const response=await connectGuest(state);state=response.state;cloudReady=response.mode==='cloud';localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('guestName').textContent=state.nickname||'Gościu';update();$('cloudStatus').textContent=cloudReady?'Wynik zapisuje się na wspólnej tablicy weselnej.':'Tryb lokalny — uzupełnij Firebase, aby uruchomić wspólny ranking.';if(cloudReady){if(selectedPhoto)$('uploadPhotoButton').disabled=false;stopGallery=listenPhotos(renderGallery,()=>{$('galleryStatus').textContent='Nie udało się pobrać galerii.';});}}catch(error){$('cloudStatus').textContent='Tryb lokalny — nie udało się połączyć z tablicą wyników.';}}
  $('drawButton').addEventListener('click',draw);$('nextButton').addEventListener('click',draw);$('doneButton').addEventListener('click',complete);$('saveNameButton').addEventListener('click',saveNickname);$('nicknameInput').addEventListener('keydown',e=>{if(e.key==='Enter')saveNickname();});$('closeAchievement').addEventListener('click',closeModal);$('resetButton').addEventListener('click',()=>{if(confirm('Zresetować wszystkie misje na tym telefonie?')){state={nickname:state.nickname,completed:[],achievements:[]};save();update();show('welcomeView');}});$('achievementModal').addEventListener('click',e=>{if(e.target===$('achievementModal'))closeModal();});$('openUploadButton').addEventListener('click',()=>show('uploadView'));$('openGalleryButton').addEventListener('click',()=>show('galleryView'));$('backFromUploadButton').addEventListener('click',()=>show('welcomeView'));$('backFromGalleryButton').addEventListener('click',()=>show('welcomeView'));$('photoInput').addEventListener('change',selectPhoto);$('uploadPhotoButton').addEventListener('click',publishPhoto);$('closePhotoModal').addEventListener('click',()=>{$('photoModal').classList.remove('is-open');});$('photoModal').addEventListener('click',event=>{if(event.target===$('photoModal'))$('photoModal').classList.remove('is-open');});
  $('guestName').textContent=state.nickname||'Gościu';update();show(state.nickname?'welcomeView':'nameView');initialiseCloud();
})();
