export const tasks = [
  ['easy','Przybij piątkę pięciu osobom, których wcześniej nie znałeś.'],
  ['easy','Powiedz komuś przy swoim stole szczery komplement.'],
  ['easy','Wznieś toast z osobą siedzącą po przeciwnej stronie stołu.'],
  ['easy','Zrób selfie z kimś poznanym dopiero na tym weselu.'],
  ['easy','Znajdź osobę w tym samym kolorze ubrania co Ty.'],
  ['easy','Uśmiechnij się do fotografa przy najbliższej okazji.'],
  ['easy','Przedstaw się komuś, z kim jeszcze dziś nie rozmawiałeś.'],
  ['easy','Zapytaj sąsiada przy stole, skąd zna Parę Młodą.'],
  ['easy','Zrób wspólne zdjęcie z całą swoją stroną stołu.'],
  ['easy','Powiedz „na zdrowie!” trzem różnym osobom.'],
  ['easy','Znajdź osobę w muszce albo z ciekawą biżuterią i powiedz jej, że świetnie wygląda.'],
  ['easy','Przybij piątkę osobie, która wydaje się najlepiej bawić.'],
  ['medium','Zaproś do tańca osobę siedzącą przy innym stole.'],
  ['medium','Znajdź gościa, który przyjechał z najdalszej miejscowości.'],
  ['medium','Zrób zdjęcie z osobą urodzoną w tym samym miesiącu co Ty.'],
  ['medium','Wypij toast z kimś, z kim jeszcze dziś nie piłeś.'],
  ['medium','Namów trzy osoby do wspólnego zdjęcia.'],
  ['medium','Znajdź świadka i podziękuj mu za organizację.'],
  ['medium','Zatańcz przez całą jedną piosenkę bez schodzenia z parkietu.'],
  ['medium','Zaproponuj wspólne zdjęcie osobom z innego stołu.'],
  ['medium','Znajdź gościa, który zna Patrycję lub Krzysztofa dłużej niż 15 lat.'],
  ['medium','Poproś kogoś o polecenie piosenki, do której koniecznie trzeba zatańczyć.'],
  ['medium','Zrób grupowe selfie z minimum czterema osobami.'],
  ['medium','Znajdź osobę o tym samym imieniu co ktoś z Twojej rodziny.'],
  ['hard','Namów pięć osób do wspólnego okrzyku „Gorzko!”.'],
  ['hard','Zrób zdjęcie z Parą Młodą — gdy będzie dobry moment.'],
  ['hard','Zaproś do tańca osobę, z którą jeszcze nie tańczyłeś.'],
  ['hard','Przekonaj trzy osoby, żeby wzniosły wspólny toast.'],
  ['hard','Znajdź najstarszego gościa i zrób z nim zdjęcie.'],
  ['hard','Przez najbliższe 10 minut nie odmawiaj zaproszenia do tańca.'],
  ['hard','Przekaż Parze Młodej osobiste życzenia.'],
  ['legend','Złota misja: pokaż ten ekran świadkowi i odbierz specjalny uścisk dłoni.'],
  ['legend','Złota misja: namów pięć osób do wspólnego zdjęcia z Parą Młodą.'],
  ['legend','Złota misja: zrób wspólne selfie z trzema różnymi pokoleniami gości.'],
  ['legend','Złota misja: jeśli DJ się zgodzi, zadedykij następny utwór Parze Młodej.']
].map(([level, text], index) => ({
  id: index + 1,
  level,
  text,
  requiresPhoto: [4, 9, 13, 16, 19, 22, 25, 30, 32, 34].includes(index + 1)
}));
